force-app/main/default/objects/Contact/fields/Volunteer_Hours__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Hours__c</fullName>
    <inlineHelpText>Total number of Volunteer Hours with a Status of Completed. Hours with other status values aren&apos;t included.</inlineHelpText>
    <label>Volunteer Hours</label>
    <summarizedField>Volunteer_Hours__c.Hours_Worked__c</summarizedField>
    <summaryFilterItems>
        <field>Volunteer_Hours__c.Status__c</field>
        <operation>equals</operation>
        <value>Completed</value>
    </summaryFilterItems>
    <summaryForeignKey>Volunteer_Hours__c.Contact__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Volunteer_Hours__c/Volunteer_Hours__c.object-meta.xml
<CustomObject>
    <label>Volunteer Hours</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>HoursID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Hours__c/fields/Volunteer_Job__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Job__c</fullName>
    <label>Volunteer Job</label>
    <referenceTo>Volunteer_Job__c</referenceTo>
    <relationshipLabel>Volunteer Hours</relationshipLabel>
    <relationshipName>Volunteer_Hours</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Volunteer_Hours__c/fields/Volunteer_Shift__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Shift__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Volunteer Shift</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Volunteer_Shift__c.Volunteer_Job__c</field>
            <operation>equals</operation>
            <valueField>$Source.Volunteer_Job__c</valueField>
        </filterItems>
        <infoMessage>You can only pick a Shift that is associated with the current Job.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Volunteer_Shift__c</referenceTo>
    <relationshipLabel>Volunteer Hours</relationshipLabel>
    <relationshipName>Volunteer_Hours</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Volunteer_Job__c/Volunteer_Job__c.object-meta.xml
<CustomObject>
    <label>Volunteer Job</label>
    <nameField>
        <label>Volunteer Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Job__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Volunteer Jobs</relationshipLabel>
    <relationshipName>Volunteer_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Volunteer_Job__c/fields/Display_on_Website__c.field-meta.xml
<CustomField>
    <fullName>Display_on_Website__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, this Volunteer Job will be included on the Available Volunteer Jobs Sites page.</inlineHelpText>
    <label>Display on Website</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Volunteer_Job__c/fields/Number_of_Volunteers__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Volunteers__c</fullName>
    <inlineHelpText>The total number of volunteers for this Job who have at least one Volunteer Hours record with a status of either Completed or Confirmed.</inlineHelpText>
    <label>Number of Volunteers</label>
    <summarizedField>Volunteer_Hours__c.Number_of_Volunteers__c</summarizedField>
    <summaryFilterItems>
        <field>Volunteer_Hours__c.Status__c</field>
        <operation>equals</operation>
        <value>Confirmed, Completed</value>
    </summaryFilterItems>
    <summaryForeignKey>Volunteer_Hours__c.Volunteer_Job__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Volunteer_Shift__c/Volunteer_Shift__c.object-meta.xml
<CustomObject>
    <label>Volunteer Shift</label>
    <nameField>
        <displayFormat>Shift-{00000}</displayFormat>
        <label>ShiftID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Shift__c/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date &amp; Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Volunteer_Shift__c/fields/Volunteer_Job__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Job__c</fullName>
    <label>Volunteer Job</label>
    <referenceTo>Volunteer_Job__c</referenceTo>
    <relationshipLabel>Volunteer Shifts</relationshipLabel>
    <relationshipName>Volunteer_Job_Slots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Volunteers_Settings__c/fields/Signup_Bucket_Account_On_Create__c.field-meta.xml
<CustomField>
    <fullName>Signup_Bucket_Account_On_Create__c</fullName>
    <inlineHelpText>The name of the Account to use when creating new Contacts during Signup. If you are using the Nonprofit Success Pack One-to-One model, leave this setting blank. If you are using the bucket model, set this to the name of the Account, usually &apos;Individual&apos;.</inlineHelpText>
    <label>Signup Bucket Account On Create</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Volunteers_Settings__c/fields/Signup_Creates_Contacts_If_No_Match__c.field-meta.xml
<CustomField>
    <fullName>Signup_Creates_Contacts_If_No_Match__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When selected, the Volunteer Signup form creates a new Contact record, if Signup Matches Existing Contacts is selected and no existing Contact is found. Otherwise, the form creates a Lead.</inlineHelpText>
    <label>Signup Creates Contacts If No Match</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Volunteers_Settings__c/fields/Signup_Matches_Existing_Contacts__c.field-meta.xml
<CustomField>
    <fullName>Signup_Matches_Existing_Contacts__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, the Volunteer Signup Page tries to match the person to an existing Contact (by First Name, Last Name, and Email), and updates their existing Contact information with the data submitted on the Volunteer Signup Page.</inlineHelpText>
    <label>Signup Matches Existing Contacts</label>
    <type>Checkbox</type>
</CustomField>

force-app-unpackaged/main/default/classes/VOL_CTRL_VolunteersJobListing_TEST.cls
/*
    Copyright (c) 2016, Salesforce.org
    All rights reserved.
    
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:
    
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Salesforce.org nor the names of
      its contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.
 
    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE 
    COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
    LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN 
    ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
    POSSIBILITY OF SUCH DAMAGE.
*/

@IsTest
private with sharing class VOL_CTRL_VolunteersJobListing_TEST {

    //==================== TEST METHOD(s) ======================================
    private static void shouldCheckCreateAccessAndInsertHours() {
        VOL_Access_TEST.Stub accessMock = new VOL_Access_TEST.Stub();
        PageReference volunteersJobListPage = Page.VolunteersJobListing;
        Test.setCurrentPage(volunteersJobListPage);
        VOL_CTRL_VolunteersJobListing.access = (VOL_Access) Test.createStub(VOL_Access.class, accessMock);
        VOL_CTRL_VolunteersJobListing jobListingCtrl = new VOL_CTRL_VolunteersJobListing();

        jobListingCtrl.contact = UTIL_UnitTest.createContact('Signup Insert ' + DateTime.now().getTime());

        jobListingCtrl.VolunteerShiftSignUp();
        // The contact creation is completed by a separate class, VOL_SharedCode
        accessMock.assertMethodCalled('checkCreateAccess', Volunteer_Hours__c.SObjectType);
        accessMock.assertMethodCalled('insertRecords', Volunteer_Hours__c.SObjectType);
    }

    /*******************************************************************************************************
    * @description test the visualforce page controller, running as the Sites Guest User, if such as user
    * exists.  if not, will run under the current user.
    * @return void
    ********************************************************************************************************/
    @IsTest
    private static void testPageWithSitesGuestUser() {
        /** Without the ability to create sharing records in apex when owd sharing is public read/write or controlled by parent, we can no longer
         * run this test as the guest user and will only run it as the admin. Commenting out so that we can reinstate
         * if / when the ability to do so becomes available
         * List<User> listU = [Select Username, UserType, Name, IsActive, Id From User where IsActive = true and UserType = 'Guest' and
        Name like '%Site Guest User%'];
        if (listU.size() > 0) {
            UTIL_UnitTest.enableElevateGuestUserAccess();
            System.debug('Running test as Sites Guest User: ' + listU[0]);
            System.runAs(listU[0]) {
                UnitTest1();
            }
        } else {
        */
            System.debug('Running test as System.');
            UnitTest1();
        //}
    }

    private static void UnitTest1() {

        // set up intial test data
        Account acc = new Account(name='Test Individual Bucket Account');
        insert acc;
        Contact con = new Contact(Lastname='Testy', Firstname='Test', Email='test@testy.com', AccountId=acc.Id);
        insert con;
        Campaign cmp = new Campaign(recordtypeid=VOL_SharedCode.recordtypeIdVolunteersCampaign, name='Test Job Campaign', IsActive=true);
        insert cmp;
        Volunteer_Job__c job = new Volunteer_Job__c(name='Job1', campaign__c=cmp.Id, Display_on_Website__c=true);
        insert job;
        Volunteer_Shift__c shift = new Volunteer_Shift__c(Volunteer_Job__c=job.Id, Duration__c=1, Start_Date_Time__c=System.now());
        insert shift;        
        
        // specify our settings        
        System.assert(VOL_SharedCode.VolunteersSettings != null);
        Volunteers_Settings__c settings = new Volunteers_Settings__c();
        settings.Signup_Creates_Contacts_If_No_Match__c = false; // this shouldn't affect this page!
        settings.Signup_Matches_Existing_Contacts__c = false;   // this shouldn't affect this page!
        settings.Signup_Bucket_Account_On_Create__c = 'Test Individual Bucket Account';
        VOL_SharedCode.getVolunteersSettingsForTests(settings);
        
        PageReference pageRef = Page.VolunteersJobListing;
        pageRef.getParameters().put('ShowJobName', '1');
        pageRef.getParameters().put('ShowDescription', '1');
        pageRef.getParameters().put('ShowLocationAddress', '1');
        pageRef.getParameters().put('ShowLocationInfo', '1');
        pageRef.getParameters().put('ShowShifts', '1');
        pageRef.getParameters().put('ShowSkills', '1');
        Test.setCurrentPage(pageRef); 

        //instantiate the controller 
        VOL_CTRL_VolunteersJobListing ctrl = new VOL_CTRL_VolunteersJobListing();
        System.assertEquals(null, ctrl.campaignIdFilter);
        System.assertEquals(true, ctrl.ShowJobName);
        System.assertEquals(true, ctrl.ShowDescription);
        System.assertEquals(true, ctrl.ShowLocationAddress);
        System.assertEquals(true, ctrl.ShowLocationInfo);
        System.assertEquals(true, ctrl.ShowShifts);
        System.assertEquals(true, ctrl.ShowSkills);
        System.assertEquals(null, ctrl.contact.Id);
        System.assertEquals(null, ctrl.jobIdSignUp);
        System.assertEquals(null, ctrl.shiftIdSignUp);
        System.assertEquals(1, ctrl.vhTemp.Number_of_Volunteers__c);
        System.assertEquals(null, ctrl.strJobDisplayName);
        System.assertEquals(null, ctrl.strShiftDisplayName);
        System.assertEquals(null, ctrl.contactIdSignUp);
        System.assertEquals(null, ctrl.volunteerHoursIdSignUp);
        System.assert(ctrl.strURLtoCSSFile == ctrl.strURLtoCSSFile);
        System.assert(ctrl.listVolunteerJobs.size() > 0);
        
        Integer cJobs = ctrl.listVolunteerJobs.size();
        Volunteer_Job__c job2 = new Volunteer_Job__c(name='Job2', campaign__c=cmp.Id, Display_on_Website__c=true);
        insert job2;
        ctrl.listVolunteerJobs = null;
        System.assertEquals(cJobs + 1, ctrl.listVolunteerJobs.size());

        ctrl.ClearVolunteerHoursIdSignUp();
        
        // sign someone up
        System.assertEquals(null, ctrl.contact.Id);
        System.assertEquals(null, ctrl.volunteerHoursIdSignUp);
        ctrl.contact.FirstName = 'Test';
        ctrl.contact.LastName = 'Testy';
        ctrl.contact.Email = 'test@testy.com';
        ctrl.jobIdSignUp = job.id;
        ctrl.shiftIdSignUp = shift.id;     
        ctrl.VolunteerShiftSignUp();
        System.assertEquals(con.Id, ctrl.contactIdSignUp);
        System.assert(ctrl.volunteerHoursIdSignUp != null);
        
        // pass cmp.Id as filter, verify only 2 jobs.
        // pass Show params with 0, verify values.
        pageRef = Page.VolunteersJobListing;
        pageRef.getParameters().put('ShowJobName', '0');
        pageRef.getParameters().put('ShowDescription', '0');
        pageRef.getParameters().put('ShowLocationAddress', '0');
        pageRef.getParameters().put('ShowLocationInfo', '0');
        pageRef.getParameters().put('ShowShifts', '0');
        pageRef.getParameters().put('ShowSkills', '0');
        pageRef.getParameters().put('campaignId', cmp.Id);
        Test.setCurrentPage(pageRef); 

        //instantiate the controller 
        ctrl = new VOL_CTRL_VolunteersJobListing();
        System.assertEquals(2, ctrl.listVolunteerJobs.size());
        System.assertEquals(cmp.Id, ctrl.campaignIdFilter);
        
        // create hours for new person, verify contact created
        ctrl.ClearVolunteerHoursIdSignUp();
        ctrl.contact.FirstName = 'New person';
        ctrl.contact.LastName = 'New person for my test';
        ctrl.contact.Email = 'newperson@volunteersjoblisting.com';
        ctrl.jobIdSignUp = job.id;
        ctrl.VolunteerShiftSignUp();
        System.assert(ctrl.contactIdSignUp != null);
        System.assert(ctrl.volunteerHoursIdSignUp != null);

        // test permissions checks
        Integer cContact = [SELECT COUNT() FROM CONTACT];
        UTIL_Describe.throwException = true;
        ctrl.ClearVolunteerHoursIdSignUp();
        ctrl.contact.FirstName = 'New person2';
        ctrl.contact.LastName = 'New person2 for my test';
        ctrl.contact.Email = 'newperson2@volunteersjoblisting.com';
        ctrl.jobIdSignUp = job.id;
        ctrl.VolunteerShiftSignUp();
        System.assertEquals(null, ctrl.contactIdSignUp);
        System.assertEquals(null, ctrl.volunteerHoursIdSignUp);
        System.assertEquals(cContact, [SELECT COUNT() FROM CONTACT]);

    }

    private static testmethod void testCampaignHierarchies() {

		//create our test data
		map<string, Campaign> mapCmp = VOL_SharedCode_TEST.mapCampaignTestHierarchy();
		ID cmpIdGrandparent = mapCmp.get('Grandparent').Id;
		System.assertNotEquals(null, cmpIdGrandparent);
    
		// verify w/ no hierarchy
        PageReference pageRef = Page.VolunteersJobListing;
        pageRef.getParameters().put('campaignId', cmpIdGrandparent);
        Test.setCurrentPage(pageRef); 
        VOL_CTRL_VolunteersJobListing ctrl = new VOL_CTRL_VolunteersJobListing();
		System.assertEquals(1, ctrl.listVolunteerJobs.size());

		// verify w/ hierarchy
        PageReference pageRef2 = Page.VolunteersJobListing;
        pageRef2.getParameters().put('campaignId', cmpIdGrandparent);
        pageRef2.getParameters().put('ShowCampaignHierarchy', '1');
        Test.setCurrentPage(pageRef2); 
        VOL_CTRL_VolunteersJobListing ctrl2 = new VOL_CTRL_VolunteersJobListing();
		System.assertEquals(mapCmp.size(), ctrl2.listVolunteerJobs.size());
    }

}